
    let btn=document.getElementById("btn");
    btn.addEventListener("click", myfunc);

    function myfunc(){
        let quote = document.getElementById("quote");

        let quotearray =
        [
        "THE BEST WAY TO FIND YOURSELF IS TO LOSE YOURSELF IN THE SERVICE OF OTHERS.",
        "IF YOU WANT TO LIFT YOURSELF UP,LIFT UP SOMEONE ELSE.",
        "THE PURPOSE OF HUMAN LIFE IS TO SERVE AND TO SHOW COMPASSION AND THE WILL TO HELP OTHERS.",
        "I BELIEVE THAT EVERY HUMAN MIND FEELS PLEASURE IN DOING GOOD TO ANOTHER.",
        "THERE IS NO SUBSTITUTE FOR HARD WORK.",
        "HARD WORK BEATS TALENT WHEN TALENT DOES NOT WORK HARD.",
        "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO.",
        "PHYSICAL FITNESS IS ONT ONLY ONE OF THE MOST IMPORTANT KEYS TO A HEALTHY BODY, BUT IT IS ALSO THE BASIS OF DYNAMIC AND CREATIVE INTELLECTUAL ACTIVITY.",
        "TAKE CARE OF YOUR BODY. IT IS THE ONLY PLACE YOU HAVE TO LIVE.",
        "EDUCATION IS THE MOST POWERFUL WEAPON WHICH YOU CAN USE TO CHANGE THE WORLD.",
        "THE BIGGEST INNOVATION OF THE 21ST CENTURY WILL BE THE INTERSECTION OF BIOLOGY AND TECHNOLOGY. A NEW ERA IS BEGINNING.",
        "SCIENCE KNOWS NO COUNTRY BECAUSE KNOWLEDGE BELONGS TO HUMANITY, AND IT IS THE TORCH WHICH ILLUMINATES THE WORLD.",
        "WITHOUT A STRONG ARMY, A NATION HAS NO PROTECTION, NO SECURITY, AND NO FUTURE.",
        "TAKE CARE OF YOUR BODY. IT IS THE ONLY PLACE YOU HAVE TO LIVE.",
        "INVESTING IN YOUR HEALTH WILL PRODUCE ENORMOUS BENEFITS IN ALL AREAS OF LIFE.",
        "A NATION THAT DESTROYS ITS SOILS DESTROYS ITSELF. FORESTS ARE THE LUNGS OF OUR LAND, PURIFYING THE AIR AND GIVING FRESH STRENGTH TO OUR PEOPLE.",
        "THE EARTH HAS MUSIC FOR THOSE WHO LISTEN.",
        "LOOK DEEP INTO NATURE, AND THEN YOU WILL UNDERSTAND EVERYTHING BETTER.",
        "CLEANLINESS IS A FUNDAMENTAL VALUE THAT OUGHT TO BE INSTALLED IN EVERY HUMAN BEING. IT IS THE CORNERSTONE OF GOOD HEALTH AND PEACE OF MIND.",
        "A NATION WHICH MAKES THE FINAL SACRIFICE FOR LIFE AND FREEDOM DOES NOT BEATEN."
        ]
        

        let ran = Math.floor(Math.random()*20);
    
        quote.textContent= quotearray[ran];

        
        }


